[package]
name = "pallet-encointer-treasuries-rpc-runtime-api"
version = "0.1.0"
authors = ["Encointer Association <info@encointer.org>"]
edition = "2021"
description = "Treasuries pallet rpc runtime api for the Encointer blockchain runtime"
homepage = "https://encointer.org"
repository = "https://github.com/encointer/pallets"
license = "GPL-3.0-or-later"

[dependencies]
# local deps
encointer-primitives = { workspace = true }

# substrate deps
frame-support = { workspace = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
sp-api = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = [
    "encointer-primitives/std",
    "frame-support/std",
    "parity-scale-codec/std",
    "scale-info/std",
    "sp-api/std",
    "sp-std/std",
]

