[package]
name = "pallet-encointer-reputation-commitments"
version = "1.2.0"
authors = ["Encointer Association <info@encointer.org>"]
edition = "2021"
description = "Reputation commitments pallet for the Encointer blockchain runtime"
homepage = "https://encointer.org"
repository = "https://github.com/encointer/pallets"
license = "GPL-3.0-or-later"

[dependencies]
approx = { version = "0.5.1", optional = true }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
log = { version = "0.4.14", default-features = false }
scale-info = { version = "2.5.0", default-features = false }

# local deps
encointer-ceremonies = { package = "pallet-encointer-ceremonies", path = "../ceremonies", default-features = false, version = "1.2.0" }
encointer-communities = { package = "pallet-encointer-communities", path = "../communities", default-features = false, version = "1.3.0" }
encointer-primitives = { path = "../primitives", default-features = false, features = ["serde_derive"], version = "1.3.0" }
encointer-scheduler = { package = "pallet-encointer-scheduler", path = "../scheduler", default-features = false, version = "1.1.0" }

# substrate deps
frame-benchmarking = { default-features = false, optional = true, version = "23.0.0" }
frame-support = { default-features = false, version = "23.0.0" }
frame-system = { default-features = false, version = "23.0.0" }
pallet-timestamp = { default-features = false, version = "22.0.0" }
sp-core = { default-features = false, version = "23.0.0" }
sp-runtime = { default-features = false, version = "26.0.0" }
sp-std = { default-features = false, version = "10.0.0" }

[dev-dependencies]
approx = "0.5.1"
sp-io = "25.0.0"
test-utils = { path = "../test-utils" }

[features]
default = ["std"]
std = [
    "codec/std",
    "log/std",
    "scale-info/std",
    "approx/std",
    # local deps
    "encointer-primitives/std",
    "encointer-ceremonies/std",
    # substrate deps
    "frame-support/std",
    "frame-system/std",
    "sp-std/std",
    "sp-runtime/std",
    "sp-core/std",
]

runtime-benchmarks = ["frame-benchmarking", "approx"]

try-runtime = [
    "frame-system/try-runtime",
]
