name: CI

on:
  push:
    branches: [ master, 'polkadot-v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cancel_previous_runs:
    name: Cancel Previous Runs
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  check:
    name: Rust check ${{ matrix.check }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        check: [ cargo build --release,
                 cargo test --all --features runtime-benchmarks --features try-runtime,
                 cargo fmt --all -- --check,
                 cargo clippy -- -D warnings
        ]
    steps:
      - uses: actions/checkout@v2

      - name: Install protoc
        run: sudo apt-get install protobuf-compiler

      - name: Setup Rust toolchain
        run: rustup show

      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.rust-target }}-${{ matrix.check }}

      - name: ${{ matrix.check }}
        run: ${{ matrix.check }}

  cargo-toml-fmt:
    runs-on: ubuntu-latest
    container: "tamasfe/taplo:0.7.0-alpine"
    steps:
      - uses: actions/checkout@v3

      - name: Run Taplo fmt
        run: taplo fmt --check

      - name: Fail-fast; cancel other jobs
        if: failure()
        uses: andymckay/cancel-action@0.2