name: CI

on:
  push:
    branches: [ master, 'polkadot-v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

# cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Rust check ${{ matrix.check }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        check: [ cargo build --release,
                 cargo test --all --features runtime-benchmarks --features try-runtime,
                 cargo clippy --all-features --all-targets -- -D warnings
        ]
    steps:
      - uses: actions/checkout@v3

      - name: Install protoc
        run: sudo apt-get install protobuf-compiler

      - name: Setup Rust toolchain
        run: rustup show

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.check }}

      - name: ${{ matrix.check }}
        run: ${{ matrix.check }}

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set rust version via common env file
        run: cat .github/env >> $GITHUB_ENV

      - name: Install nightly toolchain
        run: rustup toolchain install nightly-${{ env.RUST_NIGHTLY_VERSION }} --profile minimal --component rustfmt

      - name: cargo fmt (nightly)
        run: cargo +nightly-${{ env.RUST_NIGHTLY_VERSION }} fmt --all -- --check

  cargo-toml-fmt:
    runs-on: ubuntu-latest
    container: "tamasfe/taplo:0.7.0-alpine"
    steps:
      - uses: actions/checkout@v3

      - name: Run Taplo fmt
        run: taplo fmt --check

      - name: Fail-fast; cancel other jobs
        if: failure()
        uses: andymckay/cancel-action@0.2

  check-wasm:
    if: ${{ !startsWith(github.head_ref, 'release/') }}
    name: Check wasm build
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y protobuf-compiler
      - uses: Swatinem/rust-cache@v2
        with:
          key: check-debug-cache-
      - run: ./scripts/run_for_all_no_std_crates.sh check --no-default-features --target=wasm32-unknown-unknown